# Generated by Django 4.2.6 on 2023-11-18 18:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("prompt_templates", "0002_alter_templatepart_template"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="templatepart",
            name="template",
        ),
        migrations.AddField(
            model_name="template",
            name="parts",
            field=models.ManyToManyField(
                blank=True,
                related_name="templates",
                to="prompt_templates.templatepart",
            ),
        ),
    ]
